name: pytorch
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37h2e261b9_0
  - cudatoolkit=10.0.130=0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1d=h7b6447c_3
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=19.3.1=py37_0
  - pycparser=2.19=py37_0
  - python=3.7.6=h0371630_2
  - pytorch=1.2.0=py3.7_cuda10.0.130_cudnn7.6.2_0
  - readline=7.0=h7b6447c_5
  - setuptools=44.0.0=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - box2d-py==2.3.8
    - cachetools==4.0.0
    - chardet==3.0.4
    - cloudpickle==1.2.2
    - cycler==0.10.0
    - cython==0.29.14
    - dm-control==0.0.288483845
    - dm-env==1.2
    - dm-tree==0.1.2
    - fasteners==0.15
    - future==0.18.2
    - glfw==1.10.1
    - google-auth==1.11.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.26.0
    - gym==0.15.4
    - idna==2.8
    - imageio==2.6.1
    - kiwisolver==1.1.0
    - lxml==4.5.0
    - markdown==3.1.1
    - matplotlib==3.1.2
    - monotonic==1.5
    - mujoco-py==2.0.2.9
    - oauthlib==3.1.0
    - opencv-python==4.1.2.30
    - pathlib==1.0.1
    - protobuf==3.11.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.3.2
    - pyopengl==3.1.5
    - pyparsing==2.4.6
    - python-dateutil==2.8.1
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - roboschool==1.0.48
    - rsa==4.0
    - scipy==1.4.1
    - tensorboard==2.1.0
    - torch==1.4.0
    - torchvision==0.5.0
    - tqdm==4.42.0
    - urllib3==1.25.8
    - werkzeug==0.16.1
prefix: /its/home/at449/anaconda3/envs/pytorch

